Address removal of .tar.gz (0.5.0) and bare versions (0.6.0)

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,13 +10,18 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+if has_targz "$ASDF_INSTALL_VERSION"; then
+  release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+else
+  release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME"
+fi
 
-# Download tar.gz file to the download directory
+# Download the release file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
-
-# Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
+if has_targz "$ASDF_INSTALL_VERSION"; then
+  #  Extract contents of tar.gz file into the download directory
+  tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+  # Remove the tar.gz file since we don't need to keep it
+  rm "$release_file"
+fi
